name: Run Tests

on:
    workflow_dispatch:
    pull_request:
        branches:
            - develop

env:
    NODE_VERSION: 20

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: ${{env.NODE_VERSION}}

            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Install Dependencies
              run: npm ci

            - name: Run Unit/Integration Tests
              run: npm run test

    e2e:
        needs: test
        runs-on: ubuntu-latest

        steps:
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: ${{env.NODE_VERSION}}

            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Install Dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Run e2e Tests
              run: npm run test:e2e
